### PR TITLE
Light Mode finished !

### PR DESCRIPTION
**Pull request by black-fruit**
I made a button to control light mode and dark mode, it's working

@ramonvc

### CODE REVIEW

**Comment by black-fruit** [comment]
截屏2023-07-11 14 23 27

**Comment by black-fruit** [comment]
I think you can release this version now.

**Comment by ramonvc** [comment]
Good Work!

**Comment by black-fruit** [comment]
thank you, I'm the first time to do this

**Comment by black-fruit** [comment]
Oops! I change the port to 1342

**Comment by ramonvc** [comment]
Don't worry, I changed the port to 1338 again

**Comment by black-fruit** [comment]
Am I a Contributor now?

**Comment by ramonvc** [comment]
I sent the PR to the [pre-release branch](https://github.com/ramonvc/freegpt-webui/tree/pre-release), so once I merge it into the [main branch](https://github.com/ramonvc/freegpt-webui/tree/main), you would automatically be added as a contributor.

**Comment by black-fruit** [comment]
> I sent the PR to the [pre-release branch](https://github.com/ramonvc/freegpt-webui/tree/pre-release), so once I merge it into the [main branch](https://github.com/ramonvc/freegpt-webui/tree/main), you would automatically be added as a contributor.

I just did it. see

**Comment by black-fruit** [comment]
see #76 @ramonvc

**Comment by black-fruit** [comment]
and #75

**Pull request merged**
